//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MBrand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MBrand()
        {
            this.MProducts = new HashSet<MProduct>();
        }
        [DisplayName("Brand")]
        public int MB_id { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [DisplayName("Brand-Name")]
        public string BrandTypeName { get; set; }
        [Required]
        [DisplayName("Image")]
        [DataType(DataType.Text)]
        public string BrandImageDesc { get; set; }
        [Required]
        [DisplayName("Active")]
        public bool Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MProduct> MProducts { get; set; }
    }
}
