//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Mcity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mcity()
        {
            this.MWarehouses = new HashSet<MWarehouse>();
        }
        [DisplayName("City")]
        public int nCityID { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [DisplayName("City")]
        public string sCity { get; set; }
        [Required]
        [DisplayName("State")]
        public int nStateID { get; set; }

        public virtual Mstate Mstate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MWarehouse> MWarehouses { get; set; }
    }
}
