//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class princeshopEntities : DbContext
    {
        public princeshopEntities()
            : base("name=princeshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MBrand> MBrands { get; set; }
        public virtual DbSet<Mcity> Mcities { get; set; }
        public virtual DbSet<Mclient> Mclients { get; set; }
        public virtual DbSet<MProductType> MProductTypes { get; set; }
        public virtual DbSet<Mstate> Mstates { get; set; }
        public virtual DbSet<MSupplier> MSuppliers { get; set; }
        public virtual DbSet<MUser> MUsers { get; set; }
        public virtual DbSet<MUserType> MUserTypes { get; set; }
        public virtual DbSet<MWarehouse> MWarehouses { get; set; }
        public virtual DbSet<TProductQty> TProductQties { get; set; }
        public virtual DbSet<MProduct> MProducts { get; set; }
        public virtual DbSet<MSupplierProductMap> MSupplierProductMaps { get; set; }
        public virtual DbSet<TCart> TCarts { get; set; }
        public virtual DbSet<TOrderAllocation> TOrderAllocations { get; set; }
        public virtual DbSet<MPayStatu> MPayStatus { get; set; }
        public virtual DbSet<TOrder> TOrders { get; set; }
    }
}
