//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSupplier()
        {
            this.MSupplierProductMaps = new HashSet<MSupplierProductMap>();
            this.TOrderAllocations = new HashSet<TOrderAllocation>();
        }
        [DisplayName("Supplier")]
        public int MS_id { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [DisplayName("Supplier")]
        public string SupplierName { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [DisplayName("Adddress 1")]
        public string SupplierAddress1 { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [DisplayName("Adddress 2")]
        public string SupplierAddress2 { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [DisplayName("Adddress 3")]
        public string SupplierAddress3 { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [DisplayName("City")]
        public string SupplierCity { get; set; }
        [Required]
        [DataType(DataType.PostalCode)]
        [DisplayName("Pincode")]
        public int Pincode { get; set; }
        [Required]
        [DisplayName("Active")]
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSupplierProductMap> MSupplierProductMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOrderAllocation> TOrderAllocations { get; set; }
    }
}
