//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MWarehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MWarehouse()
        {
            this.TOrderAllocations = new HashSet<TOrderAllocation>();
        }
        [DisplayName("Warehouse")]
        public int MW_ID { get; set; }
        [Required]
        [DisplayName("Ware House")]
        public string WarehouseName { get; set; }
        [Required]
        [DisplayName("Address 1")]
        public string WarehouseAddress1 { get; set; }
        [Required]
        [DisplayName("Address 2")]
        public string WarehouseAddress2 { get; set; }
        [Required]
        [DisplayName("Address 3")]
        public string WarehouseAddress3 { get; set; }
        [Required]
        [DisplayName("City")]
        public int nCityID { get; set; }
        [Required]
        [DisplayName("State")]
        public int nStateID { get; set; }
        [Required]
        [DataType(DataType.PostalCode)]
        [DisplayName("Pincode")]
        public int Pincode { get; set; }
        [Required]
        [DisplayName("Active")]
        public bool Status { get; set; }

        public virtual Mcity Mcity { get; set; }
        public virtual Mstate Mstate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOrderAllocation> TOrderAllocations { get; set; }
    }
}
