//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TCart
    {
        [DisplayName("Cart")]
        public int nCartId { get; set; }
        [DisplayName("User")]
        public int nUserId { get; set; }
        [DisplayName("Product")]
        public int nProductId { get; set; }
        [DisplayName("Status")]
        public bool bstatus { get; set; }
    
        public virtual MProduct MProduct { get; set; }
        public virtual MUser MUser { get; set; }
    }
}
