//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOrder()
        {
            this.TOrderAllocations = new HashSet<TOrderAllocation>();
        }

        public int nTId { get; set; }
        [DisplayName("Transaction No")]
        public string sTNo { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayName("Transaction Date")]
        public System.DateTime dtTrans { get; set; }
        public int nUserID { get; set; }
        public int nProdutID { get; set; }
        [Required]
        [DisplayName("Qty")]
        [Range(1, int.MaxValue, ErrorMessage = "Quantity Should be greater than 1")]
        public decimal nQty { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        [DisplayName("Amount")]
        public decimal nAmount { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        [DisplayName("Tax")]
        public decimal nTaxAmount { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        [DisplayName("Delivery Charges")]
        public decimal nDeliveryCharges { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayName("Delivery Date")]
        public System.DateTime dtDeliveryDate { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayName("Payment Type")]
        public int nPaytype { get; set; }
        //[Required]
        //[DataType(DataType.DateTime)]
        [DisplayName("Cancel Date")]
        public Nullable<System.DateTime> dtCancel { get; set; }
        public string sCancel { get; set; }
        public bool bStatus { get; set; }

        public virtual MPayStatu MPayStatu { get; set; }
        public virtual MProduct MProduct { get; set; }
        public virtual MUser MUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOrderAllocation> TOrderAllocations { get; set; }
    }
}
