//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOrderAllocation
    {
        public int nProcessOrderID { get; set; }
        public int nOrderID { get; set; }
        public int nWarehouseID { get; set; }
        public int nClientID { get; set; }
        public int nSupplierID { get; set; }
        public bool bStatus { get; set; }
    
        public virtual Mclient Mclient { get; set; }
        public virtual MSupplier MSupplier { get; set; }
        public virtual MWarehouse MWarehouse { get; set; }
        public virtual TOrder TOrder { get; set; }
    }
}
